export const Themes={
    colors:{
    Primary:{
        '-6':'#1a2c32',
        '-5':'#2d464c',
        '-4':'#325158',
        '-3':'#356169',
        '-2':'#3b757f',
        '-1':'#438e96',
        '0':'#5faab1',
        '1':'#92cace',
        '2':'#bfe0e2',
        '3':'#ddeff0',
        '4':'#f2f9f9',
    },
    Secondary:{
        '-5':'#2f2f46',
        '-4':'#4b4969',
        '-3':'#5a587f',
        '-2':'#6b6998',
        '-1':'#7d7cab',
        '0':'#9d9ec2',
        '1':'#b4b7d1',
        '2':'#d0d2e2',
        '3':'#e5e6ef',
        '4':'#f1f2f6',
        '5':'#f7f7fb',
    },
    text:{
        white:'#ffffff',
        '0':'#efefef',
        '1':'#dcdcdc',
        '2':'#bdbdbd',
        '3':'#989898',
        '4':'#7c7c7c',
        '5':'#656565',
        '6':'#525252',
        '7':'#464646',
        '8':'#3d3d3d',
        '9':'#292929',
        black:'#000000',
    }
},
fonts: {
    bodyLarge: {
      fontFamily: 'PublicSans-Regular',
      fontSize: 16,
      fontWeight: '400',
      letterSpacing: 0.15,
      lineHeight: 24,
    },
    bodyMedium: {
      fontFamily: 'PublicSans-Regular',
      fontSize: 14,
      fontWeight: '400',
      letterSpacing: 0.25,
      lineHeight: 20,
    },
    bodySmall: {
      fontFamily: 'PublicSans-Regular',
      fontSize: 12,
      fontWeight: '400',
      letterSpacing: 0.4,
      lineHeight: 16,
    },
    default: {
      fontFamily: 'PublicSans-Regular',
      fontWeight: '400',
      letterSpacing: 0,
    },
    displayLarge: {
      fontFamily: 'PublicSans-Regular',
      fontSize: 57,
      fontWeight: '400',
      letterSpacing: 0,
      lineHeight: 64,
    },
    displayMedium: {
      fontFamily: 'PublicSans-Regular',
      fontSize: 45,
      fontWeight: '400',
      letterSpacing: 0,
      lineHeight: 52,
    },
    displaySmall: {
      fontFamily: 'PublicSans-Regular',
      fontSize: 36,
      fontWeight: '400',
      letterSpacing: 0,
      lineHeight: 44,
    },
    headlineLarge: {
      fontFamily: 'PublicSans-Regular',
      fontSize: 32,
      fontWeight: '400',
      letterSpacing: 0,
      lineHeight: 40,
    },
    headlineMedium: {
      fontFamily: 'PublicSans-Regular',
      fontSize: 28,
      fontWeight: '400',
      letterSpacing: 0,
      lineHeight: 36,
    },
    headlineSmall: {
      fontFamily: 'PublicSans-Regular',
      fontSize: 24,
      fontWeight: '400',
      letterSpacing: 0,
      lineHeight: 32,
    },
    labelLarge: {
      fontFamily: 'PublicSans-Regular',
      fontSize: 14,
      fontWeight: '500',
      letterSpacing: 0.1,
      lineHeight: 20,
    },
    labelMedium: {
      fontFamily: 'PublicSans-Regular',
      fontSize: 12,
      fontWeight: '500',
      letterSpacing: 0.5,
      lineHeight: 16,
    },
    labelSmall: {
      fontFamily: 'PublicSans-Regular',
      fontSize: 11,
      fontWeight: '500',
      letterSpacing: 0.5,
      lineHeight: 16,
    },
    titleLarge: {
      fontFamily: 'PublicSans-Regular',
      fontSize: 24,
      fontWeight: '700',
      letterSpacing: 0,
      lineHeight: 28,
    },
    titleMedium: {
      fontFamily: 'PublicSans-Regular',
      fontSize: 16,
      fontWeight: '500',
      letterSpacing: 0.15,
      lineHeight: 24,
    },
    titleSmall: {
      fontFamily: 'PublicSans-Regular',
      fontSize: 14,
      fontWeight: '500',
      letterSpacing: 0.1,
      lineHeight: 20,
    },
  },

}